"""Builds a self-contained HuggingFace repo directory for one VideoPrism variant.

Usage:
    from torch_videoprism.hf.build_repo import build_hf_repo
    build_hf_repo("videoprism_public_v1_base", out_dir="/tmp/videoprism-base-pt")

The output directory is uploadable to HF as-is (e.g. via huggingface_hub.upload_folder).

What we write:
    config.json                  — VideoPrismConfig (or VideoPrismLvtConfig)
    preprocessor_config.json     — VideoPrismVideoProcessor
    model.safetensors            — converted PyTorch weights
    modeling_videoprism.py       — wrapper + inlined port code (self-contained)
    configuration_videoprism.py  — config classes
    processing_videoprism.py     — preprocessor
    README.md                    — usage example, link to the original
"""
from __future__ import annotations

import os
import shutil
import textwrap
from pathlib import Path

import torch

from torch_videoprism.hf.configuration_videoprism import VideoPrismConfig, VideoPrismLvtConfig
from torch_videoprism.hf.modeling_videoprism import VideoPrismLvtModel, VideoPrismModel
from torch_videoprism.hf.processing_videoprism import VideoPrismVideoProcessor
from torch_videoprism.model import (
    CONFIGS,
    LVT_CONFIGS,
)
from torch_videoprism.weights import load_pretrained_weights, HF_CHECKPOINTS


# Final HF repo names (Skovorp/<name>) — keyed by upstream model name.
HF_REPO_NAMES = {
    "videoprism_public_v1_base":      "videoprism-base-f16r288-pt",
    "videoprism_public_v1_large":     "videoprism-large-f8r288-pt",
    "videoprism_lvt_public_v1_base":  "videoprism-lvt-base-f16r288-pt",
    "videoprism_lvt_public_v1_large": "videoprism-lvt-large-f8r288-pt",
}


def _make_config(model_name: str) -> VideoPrismConfig | VideoPrismLvtConfig:
    """Build the HF config for `model_name`, taking values from CONFIGS."""
    cfg = CONFIGS[model_name]
    common = dict(
        patch_size=cfg["patch_size"],
        image_size=cfg["pos_emb_shape"][1] * cfg["patch_size"],
        num_frames=cfg["pos_emb_shape"][0],
        model_dim=cfg["model_dim"],
        num_spatial_layers=cfg["num_spatial_layers"],
        num_temporal_layers=cfg["num_temporal_layers"],
        num_heads=cfg["num_heads"],
        mlp_dim=cfg["mlp_dim"],
        atten_logit_cap=cfg["atten_logit_cap"],
    )
    if model_name in LVT_CONFIGS:
        return VideoPrismLvtConfig(
            **common,
            num_auxiliary_layers=cfg["num_auxiliary_layers"],
            pooler_hidden_dim=cfg.get("pooler_hidden_dim", 4 * cfg["model_dim"]),
            pooler_num_queries=cfg.get("pooler_num_queries", 1),
        )
    return VideoPrismConfig(**common)


def _build_self_contained_modeling(out_path: Path) -> None:
    """Concatenate `torch_videoprism/model.py` + the HF wrapper classes into a
    single self-contained `modeling_videoprism.py` so HF `trust_remote_code`
    loading doesn't need the `torch_videoprism` package installed.
    """
    here = Path(__file__).resolve().parent.parent
    model_src = (here / "model.py").read_text()
    wrapper_src = (here / "hf" / "modeling_videoprism.py").read_text()

    # The shipped wrapper imports `FactorizedEncoder` / `FactorizedVideoEncoder`
    # from `torch_videoprism.model`. In the inlined file those classes are
    # defined right above, so strip the import. Also drop the wrapper's
    # `from __future__ import annotations` since the inlined model.py at the
    # top of the file already has one (and __future__ imports must be the
    # first thing in a Python module).
    cleaned_wrapper = []
    skip = False
    for line in wrapper_src.splitlines():
        if line.startswith("from torch_videoprism.model import ("):
            skip = True
            continue
        if skip:
            if line.startswith(")"):
                skip = False
            continue
        if line.startswith("from torch_videoprism.model import"):
            continue
        if line.strip() == "from __future__ import annotations":
            continue
        cleaned_wrapper.append(line)
    wrapper_src = "\n".join(cleaned_wrapper)

    header = textwrap.dedent("""\
        # NOTE: This file is auto-generated by torch_videoprism/hf/build_repo.py.
        # It bundles the PyTorch port (`torch_videoprism/model.py`) and the HF
        # wrappers in one file so users can `AutoModel.from_pretrained(...,
        # trust_remote_code=True)` without `pip install torch_videoprism`.
        # Source of truth: https://github.com/Skovorp/torch_videoprism
        """)

    out_path.write_text(header + "\n" + model_src + "\n\n" + wrapper_src)


def _copy_with_substitutions(src: Path, dst: Path, replacements: dict[str, str]) -> None:
    text = src.read_text()
    for needle, repl in replacements.items():
        text = text.replace(needle, repl)
    dst.write_text(text)


def _write_readme(out_dir: Path, model_name: str) -> None:
    is_lvt = model_name in LVT_CONFIGS
    upstream_repo, upstream_file = HF_CHECKPOINTS[model_name]
    auto_class = "AutoModel"
    output_field = "video_embeds" if is_lvt else "last_hidden_state"
    output_shape = "(B, model_dim) — L2-normalized" if is_lvt else "(B, T*N, model_dim) — token sequence"

    body = textwrap.dedent(f"""\
        ---
        license: apache-2.0
        tags:
          - video
          - vision
          - videoprism
          - feature-extraction
        library_name: transformers
        ---

        # {HF_REPO_NAMES[model_name]}

        PyTorch port of [{upstream_repo}](https://huggingface.co/{upstream_repo}) (Google DeepMind's VideoPrism).
        The original release ships JAX/Flax weights only; this repo hosts a self-contained PyTorch
        implementation that produces numerically-equivalent outputs (cosine sim 1.000000 vs the JAX
        reference). Source: <https://github.com/Skovorp/torch_videoprism>.

        ## Usage

        ```python
        from transformers import AutoModel, AutoProcessor

        model = AutoModel.from_pretrained("Skovorp/{HF_REPO_NAMES[model_name]}", trust_remote_code=True)
        processor = AutoProcessor.from_pretrained("Skovorp/{HF_REPO_NAMES[model_name]}", trust_remote_code=True)

        # Process a video file (or a list of frames / numpy / torch tensor):
        inputs = processor(videos="path/to/video.mp4", return_tensors="pt")
        outputs = model(**inputs)
        embedding = outputs.{output_field}    # shape: {output_shape}
        ```

        Frames are sampled uniformly to the model's native frame count and resized
        bilinearly to `image_size × image_size`. Pixels are scaled to `[0, 1]`.

        ## Citation

        If you use this model, please cite the original VideoPrism paper:

        ```bibtex
        @inproceedings{{zhao2024videoprism,
          title = {{VideoPrism: A Foundational Visual Encoder for Video Understanding}},
          author = {{Zhao, Long and Gundavarapu, Nitesh B. and Yuan, Liangzhe and Zhou, Hao and Yan, Shen and Sun, Jennifer J. and Friedman, Luke and Qian, Rui and Weyand, Tobias and Zhao, Yue and Hornung, Rachel and Schroff, Florian and Yang, Ming-Hsuan and Ross, David A. and Wang, Huisheng and Adam, Hartwig and Sirotenko, Mikhail and Liu, Ting and Gong, Boqing}},
          booktitle = {{ICML}},
          year = {{2024}},
        }}
        ```

        Apache-2.0 (matches upstream license).
        """)
    (out_dir / "README.md").write_text(body)


def build_hf_repo(model_name: str, out_dir: str | Path, *, weights: bool = True) -> Path:
    """Materialize a HF-loadable repo dir for one VideoPrism variant."""
    if model_name not in CONFIGS:
        raise ValueError(f"Unknown model name: {model_name!r}")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg = _make_config(model_name)
    is_lvt = model_name in LVT_CONFIGS

    # Build the model and (optionally) load pretrained weights.
    model_cls = VideoPrismLvtModel if is_lvt else VideoPrismModel
    model = model_cls(cfg)
    if weights:
        load_pretrained_weights(model.videoprism, model_name=model_name)

    # Wire auto_map so AutoConfig / AutoModel / AutoProcessor resolve via
    # trust_remote_code.
    auto_class = "VideoPrismLvtModel" if is_lvt else "VideoPrismModel"
    config_class = "VideoPrismLvtConfig" if is_lvt else "VideoPrismConfig"
    cfg.auto_map = {
        "AutoConfig":    f"configuration_videoprism.{config_class}",
        "AutoModel":     f"modeling_videoprism.{auto_class}",
        "AutoProcessor": "processing_videoprism.VideoPrismVideoProcessor",
    }

    # Save the model + config + preprocessor in HF format.
    model.config = cfg  # ensure auto_map is set on the saved config
    model.save_pretrained(out_dir, safe_serialization=True)

    processor = VideoPrismVideoProcessor(
        image_size=cfg.image_size,
        num_frames=cfg.num_frames,
    )
    processor.save_pretrained(out_dir)
    # The processor's auto_map gets serialized into preprocessor_config.json
    # only if we set it on the instance — patch in.
    import json
    pp_path = out_dir / "preprocessor_config.json"
    if pp_path.exists():
        d = json.loads(pp_path.read_text())
        d["auto_map"] = {"AutoProcessor": "processing_videoprism.VideoPrismVideoProcessor"}
        d["processor_class"] = "VideoPrismVideoProcessor"
        pp_path.write_text(json.dumps(d, indent=2))

    # Drop in the dynamic-loading Python files.
    here = Path(__file__).resolve().parent
    shutil.copy(here / "configuration_videoprism.py", out_dir / "configuration_videoprism.py")
    _copy_with_substitutions(
        here / "processing_videoprism.py",
        out_dir / "processing_videoprism.py",
        replacements={},  # processing has no torch_videoprism imports
    )
    _build_self_contained_modeling(out_dir / "modeling_videoprism.py")
    _write_readme(out_dir, model_name)

    return out_dir
